# ============================================================================
#  clean.ps1  --  remove all run-time artefacts (re-generated by one_click.ps1)
#  Source-controlled files (.ps1, .sif, .py, .md, .txt) are kept.
# ============================================================================
$ErrorActionPreference = "Continue"
Set-Location -Path $PSScriptRoot

$removed = 0
$targets = @(
    "model3d.msh",                # gmsh output (~12 MB)
    "mesh",                       # ElmerGrid output (~12 MB)
    "results",                    # ElmerSolver output
    "geom_preview.step",          # FreeCAD preview
    "test_out.log","test_err.log",# test scratch
    "run.log","sk.out","sk.py"    # scratch
)
foreach ($t in $targets) {
    $p = Join-Path $PSScriptRoot $t
    if (Test-Path $p) {
        $size = (Get-Item $p -Force).Length
        if ((Get-Item $p -Force).PSIsContainer) { $size = (Get-ChildItem $p -Recurse -File | Measure-Object Length -Sum).Sum }
        Remove-Item -Recurse -Force $p
        $removed += $size
        Write-Host ("  removed  {0,-20}  {1,8:N1} kB" -f $t, ($size/1KB))
    }
}
# clear __pycache__ if any
Get-ChildItem -Path $PSScriptRoot -Recurse -Filter __pycache__ -Directory -ErrorAction SilentlyContinue |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

$total = (Get-ChildItem -Path $PSScriptRoot -Recurse -File -ErrorAction SilentlyContinue |
          Measure-Object Length -Sum).Sum
Write-Host ""
Write-Host ("  freed   {0,8:N2} MB" -f ($removed/1MB))
Write-Host ("  current project size: {0,8:N2} MB (target < 1 MB)" -f ($total/1MB))
