#!/bin/sh -f

if test "$ELMER_LIB" = ""; then
  if  test "$ELMER_HOME" = ""; then
     LIBDIR=C:/Program Files/Elmer 26.2.1-Release/share/elmersolver/../../lib/elmersolver
     INCLUDE=C:/Program Files/Elmer 26.2.1-Release/share/elmersolver/include
  else
     LIBDIR=$ELMER_HOME/lib/elmersolver
     INCLUDE=$ELMER_HOME/share/elmersolver/include
  fi
else
  LIBDIR=$ELMER_LIB
  INCLUDE=$ELMER_LIB/../include
fi

FC=C:/msys64/mingw64/bin/gfortran.exe
cmd="$FC $*  -fallow-argument-mismatch  -DCONTIG= -DMINGW32 -DWIN32 -DHAVE_EXECUTECOMMANDLINE -DUSE_ISO_C_BINDINGS -DUSE_ARPACK -O3  -shared -I$INCLUDE -L$LIBDIR -lelmersolver"
printf "%s " $cmd
printf "\n"
$FC $*  -fallow-argument-mismatch  -DCONTIG= -DMINGW32 -DWIN32 -DHAVE_EXECUTECOMMANDLINE -DUSE_ISO_C_BINDINGS -DUSE_ARPACK -O3  -shared -I$INCLUDE -L$LIBDIR -lelmersolver
# $FC  -fallow-argument-mismatch  $*
#$FC   $INCLUDE    $*
#$FC  $INCLUDE    $* -L$LIBDIR -lelmersolver
